(:VERSION 0 :RUNS
 (((:LISP "sbcl-1.0.47.9.275.wth.kovalenko-win-x86" :LIB-WORLD "quicklisp 2011-07-30" :TIME 3530221616 :RUN-DURATION 212 :CONTACT
    (:EMAIL "avodonosov@yandex.ru"))
   (:BORDEAUX-THREADS (:STATUS :OK :OUTPUT-CHAR-LENGTH 128) :FLEXI-STREAMS (:STATUS :FAIL :OUTPUT-CHAR-LENGTH 55934) :USOCKET
    (:STATUS :FAIL :OUTPUT-CHAR-LENGTH 4269) :CL-PPCRE (:STATUS :OK :OUTPUT-CHAR-LENGTH 521) :CFFI (:STATUS :FAIL :OUTPUT-CHAR-LENGTH 7801) :TRIVIAL-FEATURES
    (:STATUS :OK :OUTPUT-CHAR-LENGTH 221) :BABEL (:STATUS :FAIL :OUTPUT-CHAR-LENGTH 570) :ALEXANDRIA (:STATUS :FAIL :OUTPUT-CHAR-LENGTH 1699)))))